version: '3.8'

services:

  api:
    build: .
    container_name: api
    ports:
      - 8081:8080
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://postgres:5432/postgres
    networks:
      - planner

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: api-db
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jdbc:postgresql://postgres:5432/postgres
    networks:
      - planner

networks:
  planner:
    driver: bridge