apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_url: amRiYzpwb3N0Z3Jlc3FsOi8vYXdzLTAtdXMtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb206NjU0My9wb3N0Z3Jlcz91c2VyPXBvc3RncmVzLm94YnlvYmZ3cnJsc2h6YXh1Z2t2JnBhc3N3b3JkPUlKOURoMlRSdUxuenRQazc=
  db_user: cG9zdGdyZXMub3hieW9iZndycmxzaHpheHVna3Y=
  db_password: SUo5RGgyVFJ1TG56dFBrNw==