apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_url: amRiYzpwb3N0Z3Jlc3FsOi8vYXdzLTAtc2EtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb206NjU0My9wb3N0Z3Jlcz91c2VyPXBvc3RncmVzLnl3cG50aXFwa2pibW1vZWZrY2plJnBhc3N3b3JkPTRmT0RFM3Vrc2E4RDVOb0gmcHJlcGFyZVRocmVzaG9sZD0w
  db_user: cG9zdGdyZXMueXdwbnRpcXBramJtbW9lZmtjamU=
  db_password: NGZPREUzdWtzYThENU5vSA==