name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # generate tag according to commit
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      # login in container registry
      - name: Login into container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
         context: .
         push: true
         tags: |
           vitorstaub/planner:${{ steps.generate_sha.outputs.sha }}
           vitorstaub/planner:latest

#      # build image
#      - name: Build docker image
#        run: docker build -t vitorstaub/planner:${{ steps.generate_sha.outputs.sha }} .
#
#      # send image
#      - name: Push image
#        run: |
#          docker push vitorstaub/planner:${{ steps.generate_sha.outputs.sha }}
#          docker tag vitorstaub/planner:${{ steps.generate_sha.outputs.sha }} vitorstaub/planner:latest
#          docker push vitorstaub/planner:latest